# -*- coding: utf-8 -*-
"""Assistida_UN4_Renan.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BprZUeg52q9ahEdUwVADIek1Yvd94rCG
"""

import os
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers, optimizers, datasets
from matplotlib import pyplot as plt
import numpy as np

(x_train_raw, y_train_raw), (x_test_raw, y_test_raw) = datasets.fashion_mnist.load_data()

print(x_train_raw.shape, y_train_raw.shape)
print(x_test_raw.shape, y_test_raw.shape)
print(x_train_raw[0])
print(y_train_raw[0])

#convertendo rótulos em variáveis
num_classes = 10
y_train = tf.keras.utils.to_categorical(y_train_raw, num_classes)
y_test = tf.keras.utils.to_categorical(y_test_raw, num_classes)
print(y_train_raw[0])
print(y_train[0])

plt.figure()
for i in range(9):
    plt.subplot(3, 3, i+1)
    plt.imshow(x_train_raw[i])
    plt.axis('off')
plt.show()

#conversão de uma matriz (imagem) de 28 x 28 para um vetor de 784 sem perder informação
x_train = x_train_raw.reshape(60000, 784)
x_test = x_test_raw.reshape(10000, 784)

#normalizar os valores dos pixels
x_train = x_train.astype('float32')/255.0
x_test = x_test.astype('float32')/255.0

# criar um modelo DE REDE NEURAL PRONFUNDA (DNN) com três camadas totalmente conectadas
model = keras.Sequential([
    layers.Dense(512, activation='relu', input_dim=784),
    layers.Dense(256, activation='relu'),
    layers.Dense(num_classes, activation='softmax')
])
model.summary()

Optimizer = optimizers.Adam(learning_rate=0.001)
model.compile(loss=keras.losses.categorical_crossentropy, optimizer=Optimizer, metrics=['accuracy'])

# ajuste os dados de treinamento ao modeo e chame o metodo fit para treinar
history = model.fit(x_train, y_train, batch_size=128, epochs=10, validation_data=(x_test, y_test), verbose=1)

score = model.evaluate(x_test, y_test, verbose=0)
print('Perda do teste:', score[0])
print('Acerto do teste:', score[1])

model.save('./model/final_DNN_model.h5')

from tensorflow.keras.models import load_model
new_model = load_model('./model/final_DNN_model.h5')
new_model.summary()

new_score = new_model.evaluate(x_test, y_test, verbose=0)
print('Perda do teste:', new_score[0])
print('Acerto do teste:', new_score[1])

# Mostrar gráfico do histórico de acurácia do modelo entre as epocas e o grafico de perdas

# Plotar a acurácia
plt.figure(figsize=(12, 5))
plt.subplot(1, 2, 1)
plt.plot(history.history['accuracy'], label='Treinamento')
plt.plot(history.history['val_accuracy'], label='Validação')
plt.title('Acurácia por Época')
plt.xlabel('Épocas')
plt.ylabel('Acurácia')
plt.legend()

# Plotar a perda
plt.subplot(1, 2, 2)
plt.plot(history.history['loss'], label='Treinamento')
plt.plot(history.history['val_loss'], label='Validação')
plt.title('Perda por Época')
plt.xlabel('Épocas')
plt.ylabel('Perda')
plt.legend()

plt.tight_layout()
plt.show()

# Gerar predict e avaliar com matriz de confusão

import numpy as np
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

# Obter previsões do modelo
y_pred_prob = model.predict(x_test)  # Retorna probabilidades

# Converter para rótulos preditos
y_pred = np.argmax(y_pred_prob, axis=1)

# Converter rótulos reais (se estiverem one-hot encoded)
y_true = np.argmax(y_test, axis=1)

# Calcular a matriz de confusão
cm = confusion_matrix(y_true, y_pred)

#exibir a matriz de confusão com rótulos
disp = ConfusionMatrixDisplay(confusion_matrix=cm)
disp.plot(cmap='Blues')
plt.title('Matriz de Confusão')
plt.show()

# Gerar acurácia, precisão, cobertura, F1, Cohen Kappa, PRF e ROC

y_pred_prob = model.predict(x_test)   # Probabilidades
y_pred = np.argmax(y_pred_prob, axis=1)   # Rótulos previstos
y_true = np.argmax(y_test, axis=1)

from sklearn.metrics import (accuracy_score, precision_score, recall_score,
                             f1_score, cohen_kappa_score, classification_report,
                             roc_curve, auc, roc_auc_score)

import matplotlib.pyplot as plt
from sklearn.preprocessing import label_binarize

# Acurácia
acc = accuracy_score(y_true, y_pred)
print(f"Acurácia: {acc:.4f}")

# Precisão, Recall e F1 (macro = média das classes)
prec = precision_score(y_true, y_pred, average='macro')
rec = recall_score(y_true, y_pred, average='macro')
f1 = f1_score(y_true, y_pred, average='macro')
print(f"Precisão (macro): {prec:.4f}")
print(f"Recall (macro): {rec:.4f}")
print(f"F1-score (macro): {f1:.4f}")

# Cohen Kappa
kappa = cohen_kappa_score(y_true, y_pred)
print(f"Cohen Kappa: {kappa:.4f}")

# Relatório completo (PRF por classe)
print("\nRelatório de Classificação:\n")
print(classification_report(y_true, y_pred))
n_classes = y_pred_prob.shape[1]
y_true_bin = label_binarize(y_true, classes=range(n_classes))

# Calcular ROC e AUC para cada classe
fpr = dict()
tpr = dict()
roc_auc = dict()
for i in range(n_classes):
    fpr[i], tpr[i], _ = roc_curve(y_true_bin[:, i], y_pred_prob[:, i])
    roc_auc[i] = auc(fpr[i], tpr[i])

# Plotar curvas ROC
plt.figure(figsize=(10, 8))
for i in range(n_classes):
    plt.plot(fpr[i], tpr[i], label=f"Classe {i} (AUC = {roc_auc[i]:.2f})")

plt.plot([0, 1], [0, 1], 'k--')
plt.xlabel('Falso Positivo')
plt.ylabel('Verdadeiro Positivo')
plt.title('Curva ROC Multiclasse')
plt.legend(loc='lower right')
plt.grid()
plt.show()

#criar um modelo de rede neural convolucional (CNN)
model = keras.Sequential()
#camada de entrada
model.add(keras.layers.Conv2D(filters=32,
                              kernel_size=5,
                              strides=(1,1),
                              padding='same',
                              activation=tf.nn.relu,
                              input_shape=(28,28,1))
)

model.add(keras.layers.MaxPool2D(pool_size=(2,2),
                                 strides=(2,2),
                                 padding='valid')
)

#segunda camada convolucional
model.add(keras.layers.Conv2D(filters=64,
                              kernel_size=3,
                              strides=(1,1),
                              padding='same',
                              activation=tf.nn.relu)
)

model.add(keras.layers.MaxPool2D(pool_size=(2,2),
                                 strides=(2,2),
                                 padding='valid')
)

#adicionar camada de dropout para tentar evitar overfitting
model.add(keras.layers.Dropout(0.25))
model.add(keras.layers.Flatten())
#camada totalmente conectada
model.add(keras.layers.Dense(units=128, activation=tf.nn.relu))
model.add(keras.layers.Dropout(0.5))
#camada de saída
model.add(keras.layers.Dense(units=10, activation=tf.nn.softmax))
model.summary()

# Commented out IPython magic to ensure Python compatibility.
# %%time
# # expansão das dimensões para os patamares originais
# X_train = x_train.reshape(60000,28,28,1)
# X_test = x_test.reshape(10000,28,28,1)
# model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
# model.fit(x=X_train, y=y_train, epochs=5, validation_data=(X_test, y_test), batch_size=128)

test_loss, test_acc = model.evaluate(X_test, y_test)
print("Acerto do teste da CNN:, %.2f"%test_acc)
print("Perda do teste da CNN:, %.2f"%test_loss)

model.save('./model/final_CNN_model.h5')
model.save('./model/final_CNN_model.keras')
#keras.saving.save_model(model, 'final_CNN_model.keras')

from tensorflow.keras.models import load_model
from tensorflow.keras.activations import softmax

#Define custom_objects to map the problematic to the correct function
custom_objects = {'softmax_v2': softmax}

new_model = load_model('./model/final_CNN_model.h5', custom_objects=custom_objects)
new_model.summary()

# Commented out IPython magic to ensure Python compatibility.
#visualize os resultados da saida do conjunto de testes
# %matplotlib inline
def res_visual(n):
    #faça predição no conjunto de testes usando new_model
    final_opt_a=np.argmax(model.predict(X_test[0:n]), axis=1)
    #print(final_opt_a)
    fig, ax = plt.subplots(nrows=int(n/5), ncols=5)
    ax = ax.flatten()
    print('resultados da PREVISÃO das 20 primeiras imagens do conjunto de teste')
    for i in range(n):
        print(final_opt_a[i], end=',')
        if int((i+1)%5) == 0:
            print('\t')
        #vendo as imagens do banco
        img = X_test[i].reshape((28,28))
        plt.axis("off")
        ax[i].imshow(img, cmap='Greys', interpolation='nearest')
        ax[i].axis("off")
    print('primeiras 20 primeiras imagens do conjunto de teste')


res_visual(30)

import streamlit as st
import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras import datasets, layers, models
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.models import load_model
import os

@st.cache_resource
def load_dataset():
    (x_train, y_train), (x_test, y_test) = datasets.fashion_mnist.load_data()

    # Normalização
    x_train = x_train / 255.0
    x_test = x_test / 255.0

    # Ajustar dimensões para CNN
    x_train = np.expand_dims(x_train, axis=-1)
    x_test = np.expand_dims(x_test, axis=-1)

    # One-hot encoding
    y_train = to_categorical(y_train, 10)
    y_test = to_categorical(y_test, 10)

    return x_train, y_train, x_test, y_test

@st.cache_resource
def get_model():
    if os.path.exists("cnn_model.h5"):
        model = load_model("cnn_model.h5")
        return model

    model = models.Sequential([
        layers.Conv2D(32, kernel_size=5, activation='relu', input_shape=(28, 28, 1)),
        layers.MaxPooling2D(),
        layers.Conv2D(64, kernel_size=3, activation='relu'),
        layers.MaxPooling2D(),
        layers.Flatten(),
        layers.Dense(128, activation='relu'),
        layers.Dense(10, activation='softmax')
    ])

    model.compile(optimizer='adam',
                  loss='categorical_crossentropy',
                  metrics=['accuracy'])

    return model

st.sidebar.title("Menu")
page = st.sidebar.selectbox(
    "Escolha uma opção:",
    ["Visualizar Dataset", "Treinar Modelo", "Avaliar Modelo", "Testar uma Imagem"]
)

x_train, y_train, x_test, y_test = load_dataset()
model = get_model()

if page == "Visualizar Dataset":
    st.title("Visualização do Fashion-MNIST")

    st.write("Exibindo 9 imagens do conjunto de treinamento:")

    fig, axes = plt.subplots(3, 3, figsize=(6, 6))
    for i, ax in enumerate(axes.flat):
        ax.imshow(x_train[i].reshape(28, 28), cmap="gray")
        ax.axis("off")

    st.pyplot(fig)

if page == "Treinar Modelo":
    st.title("Treinamento da CNN")

    epochs = st.slider("Epochs", 1, 20, 5)

    if st.button("Treinar"):
        history = model.fit(
            x_train, y_train,
            validation_split=0.1,
            epochs=epochs,
            batch_size=64,
            verbose=0
        )

        st.success("Treinamento concluído!")

        model.save("cnn_model.h5")

        st.line_chart(history.history["loss"])

if page == "Avaliar Modelo":
    st.title("Avaliação do Modelo")

    loss, acc = model.evaluate(x_test, y_test, verbose=0)

    st.write(f"**Acurácia:** {acc:.4f}")
    st.write(f"**Loss:** {loss:.4f}")

if page == "Testar uma Imagem":
    st.title("Teste de Previsão")

    index = st.number_input("Escolha um índice (0 a 9999):", 0, len(x_test)-1)

    img = x_test[int(index)]

    st.image(img.reshape(28, 28), width=200, caption="Imagem selecionada")

    if st.button("Prever"):
        pred = model.predict(img.reshape(1, 28, 28, 1))
        label = np.argmax(pred)

        st.write(f"**Classe prevista:** {label}")